[package]
name = "isabelle-core"
version = "1.1.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-cors = "0.6.4"
actix-identity = "0.6.0"
actix-multipart = "0.6.1"
actix-session = { version = "0.8", features = ["cookie-session"] }
actix-web = { version = "4", features = ["cookies"]}
argon2 = "0.5.2"
async-trait = "0.1.74"
bson = { version = "2.9.0", features = ["serde_with"] }
chrono = "0.4.26"
env_logger = "0.8.4"
futures-util = "0.3.29"
isabelle-dm = { "git" = "https://github.com/isabelle-platform/isabelle-dm" }
isabelle-plugin-api = { "git" = "https://github.com/isabelle-platform/isabelle-plugin-api" }
lazy_static = "1.4.0"
lettre = "0.10.4"
log = "0.4.0"
mongodb = { version = "2.7.1", features = [ "tokio-sync" ] }
now = "0.1.3"
parking_lot = "0.12.1"
rand = "0.8.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.96"
serde_qs = "0.12.0"
tokio = "1.37.0"
